apiVersion: v1
kind: Pod
metadata:
  name: vault-vault-status-test
spec:
  containers:
  - command:
    - sh
    - -c
    - vault status
    env:
    - name: VAULT_ADDR
      value: http://vault.default:8200
    image: vault:1.1.2
    name: vault-vault-status-test
  restartPolicy: Never
